# Generated by Django 4.2.27 on 2026-02-11 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('target_type', models.CharField(choices=[('STRUCTURE', 'Structure'), ('IHUB', 'IHUB'), ('TCU', 'TCU'), ('SOV_SYSTEM', 'Sov System'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('system_name', models.CharField(max_length=100)),
                ('structure_name', models.CharField(blank=True, max_length=100)),
                ('objective', models.CharField(choices=[('DESTROY', 'Destroy'), ('REINFORCE', 'Reinforce'), ('CAPTURE_SOV', 'Capture Sov'), ('DEFEND', 'Defend'), ('HARASS', 'Harass')], default='DESTROY', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('timer_start', models.DateTimeField(blank=True, null=True)),
                ('timer_final', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targetboard_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'timer_final', '-created_at'],
                'permissions': [('close_target', 'Can close targets (mark done/cancelled)')],
            },
        ),
        migrations.CreateModel(
            name='TargetUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='aa_targetboard.target')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
