# Generated by Django 4.2.27 on 2026-02-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_targetboard', '0002_alter_target_options_alter_targetupdate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='objective',
            field=models.CharField(choices=[('REINFORCE', 'Reinforce'), ('FINAL', 'Final'), ('DEFEND', 'Defend'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
